import './globals.css';
import { Navbar } from './components/Navbar';
import { Suspense } from 'react';
import Loading from './loading';
import NotFound from './not-found';
import Mongod from './components/Mongod';
import { Inter } from 'next/font/google';
const roboto = Inter({
	weight: '400',
	subsets: ['latin'],
});

export const metadata = {
	title: 'Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={roboto.className}>
				<Navbar />
				<Mongod />
				<Suspense fallback={<Loading />}>{children}</Suspense>
			</body>
		</html>
	);
}
